// build-posts.js
// Run by Netlify on every deploy (or when you publish a post via CMS)
// Reads all markdown files from _posts/ and writes posts.js
//
// Netlify build command: node build-posts.js
// (set this in netlify.toml)

const fs   = require("fs");
const path = require("path");

const postsDir = path.join(__dirname, "_posts");
const outFile  = path.join(__dirname, "posts.js");

// Simple front-matter parser (no dependencies needed)
function parseFrontMatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return { data: {}, content: "" };

  const data    = {};
  const content = match[2].trim();

  match[1].split("\n").forEach(line => {
    const colonIdx = line.indexOf(":");
    if (colonIdx === -1) return;
    const key = line.slice(0, colonIdx).trim();
    let   val = line.slice(colonIdx + 1).trim();

    // Remove surrounding quotes
    if ((val.startsWith('"') && val.endsWith('"')) ||
        (val.startsWith("'") && val.endsWith("'"))) {
      val = val.slice(1, -1);
    }

    // Booleans
    if (val === "true")  val = true;
    if (val === "false") val = false;

    // Numbers
    if (!isNaN(val) && val !== "") val = Number(val);

    data[key] = val;
  });

  return { data, content };
}

// Convert markdown to basic HTML (h2, h3, p, blockquote, strong, em, ul, ol)
function mdToHtml(md) {
  return md
    .split(/\n\n+/)
    .map(block => {
      block = block.trim();
      if (!block) return "";

      // Headings
      if (block.startsWith("## "))  return `<h2>${inlineFormat(block.slice(3))}</h2>`;
      if (block.startsWith("### ")) return `<h3>${inlineFormat(block.slice(4))}</h3>`;

      // Blockquote
      if (block.startsWith("> ")) {
        const text = block.split("\n").map(l => l.replace(/^>\s?/, "")).join(" ");
        return `<blockquote>${inlineFormat(text)}</blockquote>`;
      }

      // Unordered list
      if (block.split("\n").every(l => l.match(/^[-*]\s/))) {
        const items = block.split("\n").map(l => `<li>${inlineFormat(l.replace(/^[-*]\s/, ""))}</li>`).join("");
        return `<ul>${items}</ul>`;
      }

      // Ordered list
      if (block.split("\n").every(l => l.match(/^\d+\.\s/))) {
        const items = block.split("\n").map(l => `<li>${inlineFormat(l.replace(/^\d+\.\s/, ""))}</li>`).join("");
        return `<ol>${items}</ol>`;
      }

      // Horizontal rule
      if (block.match(/^[-*]{3,}$/)) return `<hr>`;

      // Paragraph
      return `<p>${inlineFormat(block.split("\n").join(" "))}</p>`;
    })
    .filter(Boolean)
    .join("\n      ");
}

function inlineFormat(text) {
  return text
    .replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>")
    .replace(/\*(.+?)\*/g,     "<em>$1</em>")
    .replace(/_(.+?)_/g,       "<em>$1</em>")
    .replace(/`(.+?)`/g,       "<code>$1</code>");
}

// Read and parse all posts
if (!fs.existsSync(postsDir)) {
  console.log("No _posts directory found — writing empty posts.js");
  fs.writeFileSync(outFile, "var BELLE_POSTS = [];\n");
  process.exit(0);
}

const files = fs.readdirSync(postsDir)
  .filter(f => f.endsWith(".md"))
  .sort();

const posts = files.map(file => {
  const raw     = fs.readFileSync(path.join(postsDir, file), "utf8");
  const { data, content } = parseFrontMatter(raw);

  return {
    id:       data.id       || 0,
    slug:     data.slug     || file.replace(".md", ""),
    title:    data.title    || "",
    excerpt:  data.excerpt  || "",
    date:     data.date     || "",
    category: data.category || "",
    readTime: data.readTime || "5 min",
    featured: data.featured === true,
    content:  "\n      " + mdToHtml(content) + "\n    "
  };
}).sort((a, b) => a.id - b.id);

const output = `/* AUTO-GENERATED by build-posts.js — do not edit manually */\n/* Edit posts via psychicbelle.com/admin or in _posts/*.md */\n\nvar BELLE_POSTS = ${JSON.stringify(posts, null, 2)};\n`;

fs.writeFileSync(outFile, output);
console.log(`posts.js written — ${posts.length} post(s) compiled`);
